package JAVA_3_3_2_exceptin_handling_mechanism;

public class Information {
	
//Exception Handling = Handling the event generated by JVM during program execution is called as "Exception Handling"
//                    To handle exceptions we havw three blocks
	           //   [i] try block [ii] catch block [iii] finally block
//	[i] try block  -    It is used to write/Declare Risky code(Exception Code)
//	                   try block is follwed by catch block/finally block
// [ii] catch block -  It is used to handle the event(Exception) which is generated by try block
               //      we can declare actual exception name & ref variable inside the catch block
	           //      Always catch block is declared after try block
	          //       we can write any no of catch blocks for single try block
//[iii]	finally block -It will execute irrespective of try and catch block, means
	         //        if whether your try/catch block is executed or not,it doesn't matter for finally block
	         // Example - ATM ---> Thank you for Using ATM

}
